# Regenerates all templates under templates/test/ that the test suite depends on.
# Big performance fixtures (medium/large/xlarge) are generated by their own
# scripts and are intentionally NOT regenerated here.
$ErrorActionPreference = "Stop"
$testDir = Join-Path $PSScriptRoot "templates\test"
New-Item -ItemType Directory -Force -Path $testDir | Out-Null

$utf8NoBom = New-Object System.Text.UTF8Encoding $false

function Write-File([string]$name, [string]$content) {
    [System.IO.File]::WriteAllText((Join-Path $testDir $name), $content, $utf8NoBom)
}

Write-File "empty.stpl" ""
Write-File "simple.stpl" '<!DOCTYPE html><html><head><title>Simple</title></head><body><h1>Hello, <%= name %></h1></body></html>'
Write-File "small.stpl" @'
<!DOCTYPE html>
<html>
<head>
    <title>Small Template</title>
    <meta charset="utf-8">
</head>
<body>
    <h1>Hello, <%= name %></h1>
    <p>This is a small template with a minimal structure.</p>
</body>
</html>
'@
Write-File "component_HEAD.stpl" '<!DOCTYPE html><html><head><meta charset="utf-8"><title>Test Page</title></head><body>'
Write-File "component_FOOT.stpl" '</body></html>'
Write-File "with_includes.stpl" '<% include!("component_HEAD.stpl"); %><main><% for item in items { %><p><%= item %></p><% } %></main><% include!("component_FOOT.stpl"); %>'
Write-File "component_shared.stpl" @'
<div class="shared-component">
    <h3>Shared Component</h3>
    <p>This component is included repeatedly to stress the minification cache.</p>
    <span class="timestamp">2024-01-01T00:00:00Z</span>
</div>
'@
Write-File "repeated_component.stpl" '<!DOCTYPE html><html><head><title>Cache Stress</title></head><body>
<% for _ in items { %><% include!("component_shared.stpl"); %><% } %>
</body></html>'

# 50 sibling components + many_includes.stpl
$main = @()
for ($i = 0; $i -lt 50; $i++) {
    $n = '{0:D2}' -f $i
    Write-File "sib_$n.stpl" "<div class=`"sibling`">Sibling $n</div>"
    $main += "<% include!(`"sib_$n.stpl`"); %>"
}
Write-File "many_includes.stpl" ($main -join '')

# Unicode / i18n stress test fixture
Write-File "unicode_heavy.stpl" @'
<!DOCTYPE html><html lang="ja"><head><meta charset="utf-8"><title>Unicode Test</title></head><body>
<% for lang in langs { %>
<section lang="<%= lang.code %>">
    <h2><%= lang.name %></h2>
    <p class="arabic">مرحباً بالعالم - العربية</p>
    <p class="chinese">你好，世界！这是一个测试模板。</p>
    <p class="japanese">こんにちは、世界！これはテストテンプレートです。</p>
    <p class="korean">안녕하세요, 세계! 이것은 테스트 템플릿입니다.</p>
    <p class="hebrew">שלום עולם! זוהי תבנית בדיקה.</p>
    <p class="thai">สวัสดีชาวโลก! นี่คือเทมเพลตทดสอบ</p>
    <p class="emoji">🚀🔥💯✨🎉👋🌍🦀⚡</p>
    <p class="rtl" dir="rtl">עברית מימין לשמאל</p>
    <p class="math">∀x ∈ ℝ: ∃y ∈ ℕ such that x &lt; y</p>
    <pre><code><%= lang.sample_code %></code></pre>
</section>
<% } %>
</body></html>
'@

Write-Host "Regenerated test fixtures in templates/test/"
